name: Flake Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest # x86_64-linux
          - macos-latest # aarch64-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - run: nix flake check -L
